-- Updated Hiking Spots Data for Cebu Region
-- 15 specific hiking spots organized by categories
-- Run this script in Supabase SQL Editor to update hiking spots

-- Clear existing data and reset sequence
DELETE FROM public.hiking_spots;
ALTER SEQUENCE hiking_spots_id_seq RESTART WITH 1;

-- Insert the 15 specific hiking spots
INSERT INTO public.hiking_spots (
    id,
    name, 
    description, 
    location, 
    region, 
    latitude, 
    longitude, 
    difficulty, 
    features, 
    image_url, 
    average_rating, 
    rating_count,
    type,
    category
) VALUES 
-- 🏔️ Peaks & Mountains (11 spots)
(
    1,
    'Osmeña Peak',
    'The highest peak in Cebu offering breathtaking 360-degree views and rolling hills covered in green grass.',
    'Dalaguete, Cebu',
    'Cebu',
    9.6167,
    123.4167,
    'moderate',
    ARRAY['summit', 'viewpoint', 'grasslands'],
    '../assets/images/spot1.jpg',
    4.8,
    245,
    'Peak',
    'Peaks & Mountains'
),
(
    2,
    'Mt. Naupa',
    'A challenging mountain hike with stunning views and diverse flora and fauna along the trail.',
    'Naga, Cebu',
    'Cebu',
    10.2089,
    123.7564,
    'hard',
    ARRAY['summit', 'challenging', 'biodiversity'],
    '../assets/images/spot2.jpg',
    4.6,
    189,
    'Peak',
    'Peaks & Mountains'
),
(
    3,
    'Mt. Kapayas',
    'A scenic mountain trail known for its lush vegetation and panoramic views of the surrounding valleys.',
    'Toledo, Cebu',
    'Cebu',
    10.3789,
    123.6456,
    'moderate',
    ARRAY['summit', 'forest', 'viewpoint'],
    '../assets/images/spot3.jpg',
    4.5,
    167,
    'Peak',
    'Peaks & Mountains'
),
(
    4,
    'Mt. Kan-Irag / Sirao Peak',
    'Popular hiking destination near Cebu City with flower gardens and cool mountain climate.',
    'Sirao, Cebu City',
    'Cebu',
    10.3512,
    123.9456,
    'easy',
    ARRAY['flowers', 'viewpoint', 'cool climate'],
    '../assets/images/spot4.jpg',
    4.4,
    198,
    'Peak',
    'Peaks & Mountains'
),
(
    5,
    'Casino Peak',
    'A lesser-known peak offering solitude and spectacular views for adventurous hikers.',
    'Sirao, Cebu City',
    'Cebu',
    10.3567,
    123.9512,
    'moderate',
    ARRAY['summit', 'solitude', 'adventure'],
    '../assets/images/spot5.jpg',
    4.3,
    134,
    'Peak',
    'Peaks & Mountains'
),
(
    6,
    'Mt. Mauyog',
    'A beautiful mountain hike with diverse ecosystems and stunning sunrise views from the summit.',
    'Barili, Cebu',
    'Cebu',
    10.1234,
    123.5678,
    'moderate',
    ARRAY['summit', 'sunrise', 'ecosystem'],
    '../assets/images/spot1.jpg',
    4.5,
    156,
    'Peak',
    'Peaks & Mountains'
),
(
    7,
    'Mt. Manunggal',
    'Historic mountain with significant cultural importance and challenging hiking trails.',
    'Balamban, Cebu',
    'Cebu',
    10.4567,
    123.7890,
    'hard',
    ARRAY['historic', 'cultural', 'challenging'],
    '../assets/images/spot2.jpg',
    4.7,
    178,
    'Peak',
    'Peaks & Mountains'
),
(
    8,
    'Mt. Lanaya',
    'The highest peak in Cebu with extremely challenging trails and spectacular sunrise views.',
    'Alegria, Cebu',
    'Cebu',
    9.7234,
    123.4567,
    'expert',
    ARRAY['summit', 'sunrise', 'challenging'],
    '../assets/images/spot3.jpg',
    4.9,
    89,
    'Peak',
    'Peaks & Mountains'
),
(
    9,
    'Ablayan Peak',
    'A scenic peak offering panoramic views and diverse wildlife along the hiking trail.',
    'Compostela, Cebu',
    'Cebu',
    10.4589,
    124.0123,
    'moderate',
    ARRAY['summit', 'wildlife', 'panoramic'],
    '../assets/images/spot4.jpg',
    4.4,
    145,
    'Peak',
    'Peaks & Mountains'
),
(
    10,
    'Mount Babag',
    'A challenging hike with rewarding 360-degree views of Cebu. Popular among serious hikers.',
    'Babag, Cebu City',
    'Cebu',
    10.3789,
    123.9234,
    'hard',
    ARRAY['summit', 'viewpoint', 'challenging'],
    '../assets/images/spot5.jpg',
    4.7,
    203,
    'Peak',
    'Peaks & Mountains'
),
(
    11,
    'Pangilatan Peak',
    'A beautiful mountain peak with lush forests and stunning views of the surrounding landscape.',
    'Minglanilla, Cebu',
    'Cebu',
    10.2456,
    123.7789,
    'moderate',
    ARRAY['summit', 'forest', 'landscape'],
    '../assets/images/spot1.jpg',
    4.5,
    167,
    'Peak',
    'Peaks & Mountains'
),
-- 🌊 Falls & Trails (4 spots)
(
    12,
    'Budlaan Falls / Kabang Falls Trail',
    'A scenic waterfall trail with crystal clear pools perfect for swimming and relaxation.',
    'Budlaan, Cebu City',
    'Cebu',
    10.3234,
    123.8567,
    'easy',
    ARRAY['waterfall', 'swimming', 'relaxation'],
    '../assets/images/spot2.jpg',
    4.6,
    189,
    'Falls',
    'Falls & Trails'
),
(
    13,
    'Dao Falls Trail',
    'A beautiful waterfall hike through lush tropical forest with multiple cascading pools.',
    'Samboan, Cebu',
    'Cebu',
    9.5234,
    123.3456,
    'moderate',
    ARRAY['waterfall', 'forest', 'cascades'],
    '../assets/images/spot3.jpg',
    4.7,
    156,
    'Falls',
    'Falls & Trails'
),
(
    14,
    'Kabutongan Falls Trail',
    'A hidden gem waterfall with pristine natural pools surrounded by tropical vegetation.',
    'Ginatilan, Cebu',
    'Cebu',
    9.6123,
    123.3789,
    'moderate',
    ARRAY['waterfall', 'hidden gem', 'natural pools'],
    '../assets/images/spot4.jpg',
    4.5,
    134,
    'Falls',
    'Falls & Trails'
),
(
    15,
    'Spartan Trail',
    'An adventurous trail system with challenging terrain and multiple scenic viewpoints.',
    'Consolacion, Cebu',
    'Cebu',
    10.3789,
    123.9567,
    'hard',
    ARRAY['adventure', 'challenging', 'viewpoints'],
    '../assets/images/spot5.jpg',
    4.8,
    178,
    'Trail',
    'Falls & Trails'
);

SELECT 'Updated hiking spots data inserted successfully! 15 specific hiking spots have been added with proper categorization.' as status;